#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dumbwhois"
name = "DumbWhois"
description.en = "simple WHOIS, IP, and ASN lookups"
description.fr = "Recherche simple de WHOIS, d'IP et d'ASN"

version = "2026.02.02~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://www.dumbware.io/"
demo = "https://dumbwhois.dumbware.io/"
admindoc = "https://www.dumbware.io/DumbWhoIs"
code = "https://github.com/DumbWareio/DumbWhois"
fund = "https://buymeacoffee.com/dumbware"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "40M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/DumbWareio/DumbWhois/archive/452838e000e5987ddefcd3d892ccf418d4390065.tar.gz"
    sha256 = "851506fbe41cc68f4368d3b38abc39a6c92371a0ea3a13d972609dd6ae407178"
    autoupdate.upstream = "https://github.com/DumbWareio/DumbWhois"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.nodejs]
    version = "22"
