#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dumbwhois"
name = "DumbWhois"
description.en = "simple WHOIS, IP, and ASN lookups"
description.fr = "Recherche simple de WHOIS, d'IP et d'ASN"

version = "1.0.0~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://www.dumbware.io/"
code = "https://github.com/DumbWareio/DumbWhois"
fund = "https://buymeacoffee.com/dumbware"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "40M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/DumbWareio/DumbWhois/archive/12703aaca9637aed85a0d2d28a9af13a86f0c94b.tar.gz"
    sha256 = "3de069010b409beb58390e2e6e6293c980f56a634e1ecd74727373128e8080b4"
    autoupdate.upstream = "https://github.com/DumbWareio/DumbWhois"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
